env:
  browser: true
  commonjs: true
  es2020: true
extends:
  - google
plugins:
  - react
parserOptions:
  ecmaVersion: 11
  sourceType: module
  ecmaFeatures:
    jsx: true
rules: {
  "quotes": ["error", "double"],
  "object-curly-spacing": ["error", "always"],
}
overrides: [
  {
    files: ["*.ts?(x)"],
    parser: "@typescript-eslint/parser",
    plugins: [
      "@typescript-eslint"
    ]
  }
]
  